### ISSUE TITLE
Fitting Rules are not included in Github SQL files

### ISSUE THREAD

**Issue by IvandaNothabeer** [Fijo/EVE-Composition-Planer#10]
There are no "default" fitting rules included in the Github repository. For private installations, all rules have to be recreated manually.

Can we get a sample of fitting rules ( eg AT 13 or AT14 ) included in the database dump please ?

**Comment by Fijo** [comment]
Sure let me work out some scripts for you!

**Comment by Fijo** [comment]
Temporary solution:
I made a db script that you can try to use please read through the header of the file before executing it.
https://github.com/Fijo/EVE-Composition-Planer/blob/master/snippets/sql/import_at_fitting_rules.sql

I'm gona make a tool that'll import those things more reliably and with less manual adjustments and so on. The downside is it'll take me a little bit.

**Comment by IvandaNothabeer** [comment]
Thanks

The rules seem to load into the database OK, but don't appear in the listed public rules. I guess this is probably because they belong to a user with ID = 31, but that user doesn't exist in my database.

I still need to do some work to try and get them to appear and will let you know how I get on.

**Comment by Fijo** [comment]
Please read the header of the sql file :)
You gotta find a the id of the user that should have the fitting rules and then change ids in that script before you execute it
good luck!
